### ISSUE TITLE
WTC-11 data link

### ISSUE THREAD

**Issue by daydayupzzl** [ma-compbio/scGHOST#2]
Your work is very interesting in the field of single cells. I want to simply run scGHOST, but the link to WTC-11 data provided in the Readme document is out of date. Could you update or provide an available link? thank you.

**Comment by kairukuma** [comment]
Hi, the account associated with the CMU box is no longer available. We've re-uploaded the WTC-11 data to a new location:

http://genome.compbio.cs.cmu.edu:8008/~kxiong/data/scghost/wtc11/

Let us know if you have any more questions.

**Comment by daydayupzzl** [comment]
Thanks a lot !
