### ISSUE TITLE
Compatible with Fast-Higashi?

### ISSUE THREAD

**Issue by AudreyBaguette** [ma-compbio/scGHOST#4]
I have single cell Hi-C samples with strong signal from structural variants that I wanted to mask, so I used Fast-Higashi instead of Higashi for them, removing regions with SVs. Can I still use scGHOST on my samples? The output format of the imputation is the same, so that's fine, but will it be a problem that I excluded some genomic regions?
Thanks!

**Comment by kairukuma** [comment]
Hi Audrey, we've used Fast-Higashi outputs with scGHOST in the past. It should run, but the results may not be the same as if you run scGHOST with Higashi outputs. Can you elaborate on what genomic regions you've excluded?

**Comment by AudreyBaguette** [comment]
What do you mean by "the results may not be the same"? Does Higashi lead to better performance, or is it "only" a matter of different results without one being better than the other?
I have a small list of breakpoints called by EagleC and I made a custom blacklist that is the ENCODE blacklist + custom list of regions of 2Mb around the breakpoints. They are all over the genome.

**Comment by kairukuma** [comment]
Fast-Higashi's outputs are different from Higashi's outputs, so you will probably get different subcompartment outputs. I can't say which result is necessarily better - it's up to you to decide based on your data.

For a small blacklist, I'm assuming the corresponding rows/columns in the scHi-C are zero'd out. In that case, they will be ignored by scGHOST and shouldn't impact the result.

**Comment by AudreyBaguette** [comment]
Awesome! Thank you very much!
Just to make sure: the blacklist option is only available in Fast-Higashi, right? Not Higashi? (I am sorry if this is not the place to ask, but since it's all from your group, I hope it's ok)

**Comment by ruochiz** [comment]
Natively, yes, only Fast-Higashi implements the function to take a blacklist.bed file. But technically you can pre-filtered your contact pairs files to remove any contacts that overlap with regions in your blacklist

**Comment by AudreyBaguette** [comment]
Great! Thank you!
